#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/.scripts}

$SCRIPTS/restaurar-cache-de-pacotes
$SCRIPTS/atualizar-e-instalar-pacotes
$SCRIPTS/configurar-hosts 172.17.6.84 sislegis.mj.gov.br
$SCRIPTS/instalar-oracle-jdk
#$SCRIPTS/instalar-haproxy
$SCRIPTS/instalar-mod_cluster
$SCRIPTS/instalar-wildfly-master
$SCRIPTS/instalar-maven
$SCRIPTS/instalar-cluster-test
#$SCRIPTS/salvar-cache-de-pacotes
