#!/bin/bash

BACKUP_DIR=${BACKUP_DIR:-/vagrant/.backup}
SLAVE_DIR=$1

[ "$SLAVE_DIR" ] || {
    echo "O diretório do slave não foi especificado!"
    exit 1
}

echo "Instalando wildfly como slave ..."

sudo pkill -u wildfly
sudo userdel -rf wildfly
sudo rm -f /etc/default/wildfly.conf /etc/init.d/wildfly /var/log/wildfly
sudo rm -rf /opt/wildfly*

WILDFLY_URL=http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz
WILDFLY=$BACKUP_DIR/${WILDFLY_URL##*/}

wget -c -O $WILDFLY $WILDFLY_URL

cd /opt
sudo tar xvfz $WILDFLY
sudo ln -s wildfly-8.2.0.Final/ wildfly
sudo useradd wildfly
sudo chown -R wildfly: wildfly-8.2.0.Final/
sudo cp wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
cat <<'EOF' | sudo tee /etc/default/wildfly.conf
JBOSS_USER=wildfly
JBOSS_MODE=domain
JBOSS_DOMAIN_CONFIG=domain.xml
JBOSS_HOST_CONFIG=host-slave.xml
STARTUP_WAIT=30
SHUTDOWN_WAIT=30
JBOSS_CONSOLE_LOG=/var/log/wildfly/console.log
EOF
sudo chkconfig wildfly on
for f in wildfly/{bin/domain.conf,domain/configuration/host-slave.xml}
do
    sudo -u wildfly patch $f < $SLAVE_DIR/$f.diff
done
sudo service wildfly start
