#!/bin/bash
set +x

COMUM=${COMUM:-/vagrant/comum}
if [ "$1" ]
then
    SLAVE=/vagrant/$1
    shift
else
    SLAVE=/vagrant/$(basename $(dirname $0))
fi

_instalar_tudo() {
    echo "Instalando tudo ..."

    $COMUM/restaurar-cache-de-pacotes
    $COMUM/atualizar-e-instalar-pacotes
    $COMUM/instalar-oracle-jdk
    $COMUM/instalar-wildfly-slave $SLAVE
    #$COMUM/salvar-cache-de-pacotes
}

op=$1
[ "$op" ] || op=tudo
type _instalar_$op &> /dev/null && _instalar_$op || { 
    echo "função \"_instalar_$op\" não encontrada!"
    exit 1
}
