#!/bin/bash

BACKUP_DIR=${BACKUP_DIR:-/vagrant/.backup}

echo "Instalando o wildfly no master ..."

sudo userdel -rf wildfly
sudo rm -f /etc/default/wildfly.conf /etc/init.d/wildfly
sudo rm -rf /opt/wildfly*

WILDFLY_URL=http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz
WILDFLY=$BACKUP_DIR/${WILDFLY_URL##*/}

wget -c -O $WILDFLY $WILDFLY_URL

cd /opt
sudo tar xvfz $WILDFLY
sudo ln -s wildfly-8.2.0.Final/ wildfly
sudo useradd wildfly
sudo chown -R wildfly: wildfly-8.2.0.Final/
sudo cp wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
cat <<'EOF' | sudo tee /etc/default/wildfly.conf
JBOSS_USER=wildfly
JBOSS_MODE=domain
JBOSS_DOMAIN_CONFIG=domain.xml
JBOSS_HOST_CONFIG=host-master.xml
STARTUP_WAIT=30
SHUTDOWN_WAIT=30
JBOSS_CONSOLE_LOG=/var/log/wildfly/console.log
EOF
sudo chkconfig wildfly on
for f in wildfly/{bin/domain.conf,domain/configuration/domain.xml}
do
    sudo -u wildfly patch $f < /vagrant/master/$f.diff
done
for f in wildfly/domain/configuration/mgmt-*
do
    sudo -u wildfly cp /vagrant/master/$f $(dirname $f)
    sudo -u wildfly chmod 600 $f
done
sudo service wildfly start
