#!/bin/bash

configurar() {
    local f=/etc/hosts

    grep -q "^$1.*$2" $f || { echo -e "$1\t$2" | sudo tee -a $f; }
}

if [ "$1" -a "$2" ]
then
    configurar $1 $2
else
    configurar 172.17.6.84 sislegis.mj.gov.br
    configurar 172.17.6.83 keycloak.mj.gov.br
fi
