#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}

sudo yum -y install haproxy

f=etc/haproxy/haproxy.cfg
sudo cp $BASE_DIR/`hostname -s`/haproxy/$f $(dirname /$f)

sudo chkconfig haproxy on
sudo service haproxy start
