#!/bin/bash
set +x

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/.scripts}

$SCRIPTS/restaurar-cache-de-pacotes
$SCRIPTS/atualizar-e-instalar-pacotes
$SCRIPTS/instalar-oracle-jdk
$SCRIPTS/instalar-wildfly-slave
#$SCRIPTS/salvar-cache-de-pacotes
