#!/bin/bash
set +x

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/.scripts}
if [ "$1" ]
then
    SLAVE=$BASE_DIR/$1
    shift
else
    SLAVE=$BASE_DIR/$(basename $(dirname $0))
fi

_instalar_tudo() {
    echo "Instalando tudo ..."

    $SCRIPTS/restaurar-cache-de-pacotes
    $SCRIPTS/atualizar-e-instalar-pacotes
    $SCRIPTS/instalar-oracle-jdk
    $SCRIPTS/instalar-wildfly-slave $SLAVE
    #$SCRIPTS/salvar-cache-de-pacotes
}

op=$1
[ "$op" ] || op=tudo
type _instalar_$op &> /dev/null && _instalar_$op || { 
    echo "função \"_instalar_$op\" não encontrada!"
    exit 1
}
