#!/bin/bash
set +x

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS_DIR=$BASE_DIR/.scripts
SLAVE=`hostname -s`
MASTER_IP=172.17.6.84
SLAVE_IP=`cat $BASE_DIR/$SLAVE/ip`
BACKUP_DIR=${BACKUP_DIR:-$BASE_DIR/.backup}; mkdir -p $BACKUP_DIR
POSTGRESQL_JDBC_DRIVER_URL=http://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc41.jar
POSTGRESQL_JDBC_DRIVER=${POSTGRESQL_JDBC_DRIVER_URL##*/}
WILDFLY_URL=http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz
WILDFLY=$BACKUP_DIR/${WILDFLY_URL##*/}

echo "Instalando wildfly numa máquina slave ($SLAVE) ..."

sudo pkill -u wildfly
sudo userdel -rf wildfly
sudo rm -rf /etc/default/wildfly.conf /etc/init.d/wildfly /var/log/wildfly
sudo rm -rf /opt/wildfly*

wget -c -O $WILDFLY $WILDFLY_URL

cd /opt
sudo tar xvfz $WILDFLY
sudo ln -s wildfly-8.2.0.Final/ wildfly
sudo useradd wildfly
sudo chown -R wildfly: wildfly-8.2.0.Final/
sudo cp wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
cat <<'EOF' | sudo tee /etc/default/wildfly.conf
JBOSS_USER=wildfly
JBOSS_MODE=domain
JBOSS_DOMAIN_CONFIG=domain.xml
JBOSS_HOST_CONFIG=host-slave.xml
STARTUP_WAIT=30
SHUTDOWN_WAIT=30
JBOSS_CONSOLE_LOG=/var/log/wildfly/console.log
EOF
sudo chkconfig wildfly on

f=wildfly/bin/domain.conf
sudo -u wildfly patch $f < $SCRIPTS_DIR/wildfly-slave/$f.diff
sudo -u wildfly sed -i \
-e "s/JBOSS_DOMAIN_MASTER_ADDRESS/$MASTER_IP/g" \
-e "s/JBOSS_BIND_ADDRESS/$SLAVE_IP/g" \
$f

f=wildfly/domain/configuration/host-slave.xml
sudo -u wildfly patch $f < $SCRIPTS_DIR/wildfly-slave/$f.diff
sudo -u wildfly sed -i "s/HOSTNAME/$SLAVE/g" $f

wget -c -O $BACKUP_DIR/$POSTGRESQL_JDBC_DRIVER $POSTGRESQL_JDBC_DRIVER_URL

driver_dir=wildfly/modules/system/layers/base/org/postgresql/main
sudo -u wildfly mkdir -p $driver_dir
sudo -u wildfly cp $BACKUP_DIR/$POSTGRESQL_JDBC_DRIVER $driver_dir/
cat <<EOF | sudo -u wildfly tee $driver_dir/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.postgresql">
    <resources>
        <resource-root path="$POSTGRESQL_JDBC_DRIVER"/>
    </resources>
    <dependencies>
        <module name="javax.api"/>
        <module name="javax.transaction.api"/>
    </dependencies>
</module>
EOF

sudo service wildfly start
