#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/.scripts}

_instalar() {
    $SCRIPTS/restaurar-cache-de-pacotes
    $SCRIPTS/atualizar-e-instalar-pacotes
    $SCRIPTS/configurar-hosts 172.17.6.84 sislegis.mj.gov.br
    $SCRIPTS/instalar-oracle-jdk
    $SCRIPTS/instalar-haproxy
    $SCRIPTS/instalar-wildfly-master
    $SCRIPTS/salvar-cache-de-pacotes
}

_instalar
