#!/bin/bash
set +x

BASE_DIR=${BASE_DIR:-/vagrant}
source $BASE_DIR/config || exit $?

BACKUP_DIR=${BACKUP_DIR:-$BASE_DIR/.backup}; mkdir -p $BACKUP_DIR
POSTGRESQL_JDBC_DRIVER_URL=http://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc41.jar
POSTGRESQL_JDBC_DRIVER=${POSTGRESQL_JDBC_DRIVER_URL##*/}
WILDFLY_URL=http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz
WILDFLY=$BACKUP_DIR/${WILDFLY_URL##*/}

echo "Instalando o wildfly na máquina master ($master) ..."

sudo pkill -u wildfly
sudo userdel -rf wildfly
sudo rm -f /etc/default/wildfly.conf /etc/init.d/wildfly
sudo rm -rf /opt/wildfly*

wget -c -O $WILDFLY $WILDFLY_URL

cd /opt
sudo tar xvfz $WILDFLY
sudo ln -s wildfly-8.2.0.Final/ wildfly
sudo useradd wildfly
sudo chown -R wildfly: wildfly-8.2.0.Final/
sudo cp wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
cat <<'EOF' | sudo tee /etc/default/wildfly.conf
JBOSS_USER=wildfly
JBOSS_MODE=domain
JBOSS_DOMAIN_CONFIG=domain.xml
JBOSS_HOST_CONFIG=host-master.xml
STARTUP_WAIT=30
SHUTDOWN_WAIT=30
JBOSS_CONSOLE_LOG=/var/log/wildfly/console.log
EOF
sudo chkconfig wildfly on
for f in wildfly/{bin/domain.conf,domain/configuration/{domain.xml,host-master.xml}}
do
    sudo -u wildfly patch $f < $BASE_DIR/$master/$f.diff
done
for f in wildfly/domain/configuration/mgmt-*
do
    sudo -u wildfly cp $BASE_DIR/$master/$f $(dirname $f)
    sudo -u wildfly chmod 600 $f
done

wget -c -O $BACKUP_DIR/$POSTGRESQL_JDBC_DRIVER $POSTGRESQL_JDBC_DRIVER_URL

driver_dir=wildfly/modules/system/layers/base/org/postgresql/main
sudo -u wildfly mkdir -p $driver_dir
sudo -u wildfly cp $BACKUP_DIR/$POSTGRESQL_JDBC_DRIVER $driver_dir/
cat <<EOF | sudo -u wildfly tee $driver_dir/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.postgresql">
    <resources>
        <resource-root path="$POSTGRESQL_JDBC_DRIVER"/>
    </resources>
    <dependencies>
        <module name="javax.api"/>
        <module name="javax.transaction.api"/>
    </dependencies>
</module>
EOF

sudo service wildfly start
