#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}
BACKUP_DIR=${BACKUP_DIR:-$BASE_DIR/.backup}
VAR_CACHE=$BACKUP_DIR/var_cache.tar

# configura o Yum para manter o cache de pacotes
sudo sed -i 's/\(keepcache=\).*/\11/' /etc/yum.conf

# restaura o cache de pacotes do backup, se existir
[ -f $VAR_CACHE ] && sudo tar xvfP $VAR_CACHE
